# Bukkit configuration - optimized for many bots
settings:
  allow-end: false
  warn-on-overload: false
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: -1
  query-plugins: false
  deprecated-verbose: false
  shutdown-message: Server shutting down
  minimum-api: none
  use-map-color-cache: false
spawn-limits:
  monsters: 0
  animals: 10
  water-animals: 0
  water-ambient: 0
  water-underground-creature: 0
  axolotls: 0
  ambient: 0
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 400
  monster-spawns: -1
  water-spawns: -1
  water-ambient-spawns: -1
  water-underground-creature-spawns: -1
  axolotl-spawns: -1
  ambient-spawns: -1
  autosave: 6000
